# Includes complete Jenkins configuration in order to run pipeline
# To install on your own cluster, run:
# helm --namespace jenkins --name jenkins -f ./jenkins-values.yaml install stable/jenkins

Master:
  Image: "jenkins/jenkins"
  ImageTag: "lts-alpine"
  InstallPlugins:
      - blueocean:1.10.1
      - credentials-binding:1.17
      - git:3.9.1
      - kubernetes:1.14.3
      - workflow-aggregator:2.6
      - workflow-job:2.31