# Includes complete Jenkins configuration in order to run pipeline
# To install on your own cluster, run:
# helm --namespace jenkins --name jenkins -f ./jenkins-values.yaml install stable/jenkins

Master:
  Image: "jenkins/jenkins"
  ImageTag: "lts-alpine"
  InstallPlugins:
      - blueocean:1.10.1
      - credentials-binding:1.17
      - git:3.9.1
      - kubernetes:1.14.3
      - workflow-aggregator:2.6
      - workflow-job:2.31

  ScriptApproval:
      - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
      - "new groovy.json.JsonSlurperClassic"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods leftShift java.util.Map java.util.Map"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods split java.lang.String"
      - "method java.util.Collection toArray"
      - "staticMethod org.kohsuke.groovy.sandbox.impl.Checker checkedCall java.lang.Object boolean boolean java.lang.String java.lang.Object[]"
      - "staticMethod org.kohsuke.groovy.sandbox.impl.Checker checkedGetProperty java.lang.Object boolean boolean java.lang.Object"